const ADD_TODO = "ADD_TODO";
const DELETE_TODO = "DELETE_TODO";
const MARK_COMPLETED = "MARK_COMPLETED";
const MARK_IN_PROGRESS = "MARK_IN_PROGRESS";

export { ADD_TODO, DELETE_TODO, MARK_COMPLETED, MARK_IN_PROGRESS };
